server:
  port: 8763
spring:
  application:
    name: eureka-server
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
        defaultZone: http://peer1:8761/eureka/, http://peer2:8762/eureka/
    fetch-registry: true
    register-with-eureka: true